[theme]
base = "dark"
primaryColor = "#4f924f"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1e1e1e"
textColor = "#ffffff"
font = "sans serif"

[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false